### ISSUE TITLE
Postgres/source: only master host is used after providing multiple hosts

### ISSUE THREAD

**Issue by rifler** [doublecloud/transfer#129]
With below config only master host is used, according to datatransfer logs and rds logs/metrics:
```yaml
transfer_spec:
  type: SNAPSHOT_AND_INCREMENT
  src:
    type: pg
    params:
      Hosts:
        - master.amazonaws.com
        - replica.amazonaws.com
      Port: 5432
```

I would expect that:
- replication slot would be created on master
- snapshot (job) would be done from replica
- replication (sts) would work from master
