### ISSUE TITLE
Yt dest partition use UTC+3

### ISSUE THREAD

**Issue by ykuc** [doublecloud/transfer#136]
I use partition by column `current_server_timestamp`, but in sending data use partition UTC+3 `//home/path_to_table/partition`
Not critical, but strange

Example:

current_server_timestamp: 2024-12-06T20:31:04.619572Z 
partition: 2024-12-06 

current_server_timestamp: 2024-12-06T21:01:06.177199Z
partition: 2024-12-07 

Config:
```yaml
      Rotation:
        TimeColumn: "current_server_timestamp"
        PartType: "d"
        PartSize: 1
        KeepPartCount: 700
        TableNameTemplate: ""
      Cleanup: "Disabled"
```

<img width="443" alt="image" src="https://github.com/user-attachments/assets/79712c8f-0ba9-46f6-8b18-eec6afccebf4">
