### ISSUE TITLE
Not clear how to apply existing transformations

### ISSUE THREAD

**Issue by work-vv** [doublecloud/transfer#200]
Document  [https://doublecloud.github.io/transfer/docs/concepts/transformations.html](url)  explain steps like so: _In Transformer list, click Add transformer to create a set of transformation rules._  Not clear which UI is mentioned and how to apply transformations in cli script. Config options have poor explanations in docs as well. Could someone guide me how to tackle with transformations, please.

**Comment by laskoviymishka** [comment]
Refactor doc, now there is yaml-demo for each transformer and full example at the end:

```

```yaml
id: test
type: SNAPSHOT_AND_INCREMENT
src:
  type: mysql
  params:
    Host: mysql
    User: myuser
    Password: mypassword
    Database: mydb
    Port: 3306
dst:
  type: ch
  params:
    ShardsList:
      - Hosts:
          - clickhouse
    HTTPPort: 8123
    NativePort: 9000
    Database: default
    User: default
    Password: "ch_password"
transformation:
  debugmode: false
  transformers:
    - sql:
        query: SELECT * FROM table
        tables:
          includeTables:
            - public.test
          excludeTables: null
      transformerId: ""
    - maskField:
        columns:
          - address
        maskFunctionHash:
          userDefinedSalt: random_secret_string
        tables:
          includeTables:
            - public.test
          excludeTables: null
      transformerId: ""
    - dbt:
        ProfileName: 'my_dbt_profile'
        GitBranch: 'main'
        GitRepositoryLink: 'https://github.com/myorg/mydbtproject'
        Operation: 'run'
      transformerId: ""
errorsoutput: null
data_objects:
  include_objects:
    - public.test
type_system_version: 9
```
```
