### ISSUE TITLE
Add Mysql binlog position/starttime logic

### ISSUE THREAD

**Issue by work-vv** [doublecloud/transfer#209]
Binlog start position or/and binlog startime missed  in mysql adapter config, though pointer used in runtime logic. It looks like a minor change but huge improvement which can reduce replication time in some cases, such as quick recovering replication on top of existing snapshot.

**Comment by laskoviymishka** [comment]
Thought about this, but not sure regards to end user flow, any ideas how it can be used from end user perspective?

**Comment by work-vv** [comment]
Common usecase. Sync between mysql and ch failed in production at midnight) Binlog is huge and replicate it from the beginning is not effective way to restore and sync state again. But with suggested functionality we can restart replication and sync process from midnight.

**Comment by laskoviymishka** [comment]
Yeah, but how this shall be operated on ops level? As an extra option?

**Comment by work-vv** [comment]
As soon as  incremenal snaphot might be differ or not available from provider to provide I would put time tag or pointer for now as an optional  parameter for mysql connector and fill it in transfer config source connector options. Also it would be nice to show actual value in logs on data transfer finished or failed.

**Comment by Poltoruhin** [comment]
Hello gentlemens!
Just wanna say that this enhancement would be much appreciated. We trying to use CH for OLAP alongside with main MySQL db and the case described by @work-vv seems very possible.

**Comment by laskoviymishka** [comment]
@work-vv @Poltoruhin it's still unclear to me how it would work.
If the idea is to allow transfer to recover after binlog rotate - then, it's a case for increment-only transfer where [SyncBinlog](https://github.com/doublecloud/tross/blob/2e7db31a29c7e44b52df0122c1654c640989debc/pkg/providers/mysql/sync_binlog_position.go#L34) procedure will recover binlog on a restart.

**Comment by laskoviymishka** [comment]
Let me rephrase, we have following config:

```
id: test
type: SNAPSHOT_AND_INCREMENT
src:
  type: mysql
  params:
    Host: mysql
    User: myuser
    Password: mypassword
    Database: mydb
    Port: 3306
dst:
  type: ch
  params:
    ....
```

Let's add a new field: `startpos`, as binlog position / gtid-id

```
id: test
type: INCREMENT_ONLY
src:
  type: mysql
  params:
    Host: mysql
    User: myuser
    Password: mypassword
    Database: mydb
    Port: 3306
    StartPos:
      type: binlog
      value: "binlog_0001/123"
dst:
  type: ch
  params:
    ....
```

So once transfer is started - we start not from a head of a binlog, but exactly from `"binlog_0001/123"`.

There is a question: what to do if there is no such binlog file? (i.e. it's got rotated).
