### ISSUE TITLE
mongo connector BatchFlushInterval does not allow use golang string suffixes.

### ISSUE THREAD

**Issue by BorisTyshkevich** [doublecloud/transfer#213]
when I set: 

```
src:
  type: mongo
  params:
    batchingparams:
      BatchFlushInterval: 5s
```

Got an error:

```
BatchingParams.BatchFlushInterval' expected type 'time.Duration', got unconvertible type 'string', value: '5s'
```

version 0.0.18rc

Expected that all golang time spec construction will work as they should.

Boris.
