### ISSUE TITLE
multiple topics consuming by Kafka connector

### ISSUE THREAD

**Issue by BorisTyshkevich** [doublecloud/transfer#214]
For all DB connectors (mongo, mysql, postgres) Transfer can pull data from many tables. However, for Kafka it's possible to specify only 1 topic:

```
      Topic: "my-kafka-topic"
```

It would be great, if Transfer can consume from multiple topics. The very same as Clickhouse's Kafka Engine.

```
src:
  type: kafka
  params:
    topics:
    - topic1
    - topic2
    - topic3
```

Boris.
