### ISSUE TITLE
Helm questions

### ISSUE THREAD

**Issue by BorisTyshkevich** [doublecloud/transfer#220]
I see such in docs:

1. **SNAPSHOT_ONLY**: A one-time `Job` for uploading a snapshot of data.
2. **INCREMENT_ONLY**: A continuous data replication `StatefulSet`.
3. **SNAPSHOT_AND_INCREMENT**: A `Job` for a one-time data snapshot upload followed by a continuous replication `StatefulSet` after the job completes.

Question to the Helm Chart maintainer:

1. Why StatefulSet is used?  Is there any state for trcli?  Where is it stored?
2. How should SNAPSHOT_AND_INCREMENT work with Job and StatefulSet together?  Why `trcli replicate` will wait `trcli activate` ? How do they sync?

BTW:
 I'm working on a Helm chart that can run multiple Transfer tasks in different Deployments—and thinking of publishing it or incorporating it into the existing one.

values.yaml looks like:

```
transfers:
  - name: task1
    type: SNAPSHOT_AND_INCREMENT       # Options: SNAPSHOT_ONLY, INCREMENT_ONLY, SNAPSHOT_AND_INCREMENT (default)
    src:  db1                                                       # ref to db-hosts and Secrets
    dst:  clickhouse                                          # ref to db-hosts and Secrets
    coordinator: coordinator_s3                     # ref to coordinator_s3

  - name: task2
    src: db1
    dst:  clickhouse
    coordinator: coordinator_s3

  - name: task3
    src: db2
    dst:  clickhouse
```

default src/dst hosts settings for different tasks are placed in the db-hosts directory. Secrets are used via ENV variables.

Particular transfer.yaml is merged from:
- config/task1.yaml  (mostly table and database names configured here)
- db-hosts/db1.yaml
- db-hosts/clickhouse.yaml
